Remove vuln location and change vuln title .
Ostorlab/agent_osv pull request #19
Opened 2023-07-17 16:30 UTC by mohsinenar

- Remove Vuln location.
Example of findings:

![image](https://github.com/Ostorlab/agent_osv/assets/15703728/3af8ada3-aa6e-4fa4-a480-656254fde085)

2023-07-17 17:29 UTC, amine3 commented on agent/osv_output_handler.py
> +                entry.title = f"Use of Outdated Vulnerable Component: {package_name} {package_version}"
{package_name}@{package_version}

2023-07-17 17:31 UTC, 3asm requested changes

2023-07-17 17:31 UTC, 3asm commented on agent/osv_output_handler.py
> +    )
```suggestion
    technical_detail = (
            f"Dependency `{package_name}` with version `{package_version}` found in `{file_type}` has a security issue. The issue `{summary}` is identified by CVE `{','.join(vuln_aliases)}`."
    )
```

2023-07-17 18:21 UTC, amine3 approved these changes

2023-07-18 09:59 UTC, deadly-panda approved these changes

2023-07-18 14:25 UTC, amine3 approved these changes

2023-07-18 14:25 UTC, 3asm approved these changes
Nice work.

2023-07-18 14:26 UTC, merged