Correct OSV technical detail
Ostorlab/agent_osv pull request #39
Opened 2024-02-02 17:35 UTC by elyousfi5

2024-02-02 17:47 UTC, 3asm requested changes

2024-02-02 17:47 UTC, 3asm commented on agent/api_manager/osv_service_api.py
> +                f"Dependency `{package_name}` with version `{vuln.fixed_version}`"
Should be the version we got. Fixed version is in the recommendation.

2024-02-05 08:30 UTC, PiranhaSa approved these changes

2024-02-05 12:27 UTC, 3asm requested changes

2024-02-05 15:21 UTC, merged