fix/bug grouping findings can report wrong vulnerabilities
Ostorlab/agent_osv pull request #47
Opened 2024-02-15 17:23 UTC by oussamaessaji

Do not merge until https://github.com/Ostorlab/agent_osv/pull/46 gets merged

2024-02-15 17:42 UTC, deadly-panda commented on tests/osv_agent_test.py
> +    osv_api_output_risk_invalid: dict[str, Any],
Where is this used ?

2024-02-15 17:42 UTC, 3asm requested changes

2024-02-15 17:42 UTC, 3asm commented on agent/api_manager/osv_service_api.py
> +        return None
This empty check should not be here.

2024-02-15 17:44 UTC, deadly-panda commented on tests/osv_agent_test.py
> +    msg = message.Message.from_data(selector, data=msg_data)
I would just mock the response.. If a cve is associated with this fingerprint the unit test will fail.

2024-02-15 18:33 UTC, ErebusZ commented on agent/osv_output_handler.py
> +        return []
you return empty list here but the check you did is for None value

2024-02-16 08:43 UTC, 3asm approved these changes

2024-02-16 08:44 UTC, merged